export const LOGIN_lOADING = "LOGIN_lOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ADMIN_REQUEST_lOADING = "ADMIN_REQUEST_lOADING";
export const ADMIN_REQUEST_SUCCESS = "ADMIN_REQUEST_SUCCESS";
export const ADMIN_REQUEST_FAIL = "ADMIN_REQUEST_FAIL";

export const ISAUTHENTICATED_STATUS = "ISAUTHENTICATED_STATUS";

export const BLOGS_REQUEST_lOADING = "BLOGS_REQUEST_lOADING";
export const BLOGS_REQUEST_SUCCESS = "BLOGS_REQUEST_SUCCESS";
export const BLOGS_REQUEST_FAIL = "BLOGS_REQUEST_FAIL";

export const BLOG_REQUEST_FAIL = "BLOG_REQUEST_FAIL";

export const BLOG_DELETE_FAIL = "BLOG_DELETE_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
